// Auto-generated by bini-deploy - do not edit.
// Add routes by creating files in src/app/api/
// Generated at: 2026-09-10T05:53:07.201Z

import { Hono } from 'hono';
import { cors } from 'hono/cors';
import _route0 from '../src/app/api/chat.js';
import _route1 from '../src/app/api/hello.js';

const app = new Hono();
app.use('/api/*', cors({ origin: '*', allowMethods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowHeaders: ['Content-Type','Authorization'] }));
app.route('/api', _route0);
app.route('/api', _route1);

export default app;
