// ⚠️  Auto-generated by bini-router on every build — do not edit.
// Add routes by creating files in src/app/api/ only.
// Generated at: 2026-05-03T19:18:56.919Z

import { Hono } from 'hono';
import { cors } from 'hono/cors';
import _route0 from '../src/app/api/chat';

const app = new Hono();
app.use('/api/*', cors({ origin: '*', allowMethods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowHeaders: ['Content-Type','Authorization'] }));
app.all('/api/chat', async (c) => { 
    try {
      const r = await _route0(c.req.raw);
      return r instanceof Response ? r : c.json(r);
    } catch (error) {
      console.error(`API Error on ${c.req.path}:`, error);
      return c.json({ error: 'Internal Server Error' }, 500);
    }
  });

export const config = { runtime: 'edge' };
export default app.fetch;
